[source.crates-io]
replace-with = "vendored-sources"

[source."git+https://github.com/ccnlui/fortytwo"]
git = "https://github.com/ccnlui/fortytwo"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
